"""
TEST: Verify SQL Query Generation & Execution for Excel Sheets

This test shows:
1. ✅ File upload (Excel)
2. ✅ Chunks creation
3. ✅ Q&A request
4. ✅ SQL Query generated by LLM
5. ✅ SQL Query executed against SQLite
6. ✅ Results returned with full details
"""

import requests
import json
import time
from datetime import datetime

BASE_URL = "http://127.0.0.1:8002"

# Generate unique users for each run
timestamp = int(datetime.now().timestamp())
owner_email = f"owner{timestamp}@test.com"
emp_email = f"emp{timestamp}@test.com"

print("=" * 80)
print("EXCEL SHEET SQL QUERY EXECUTION TEST")
print("=" * 80)

# Step 1: Register owner
print("\n[1/7] Registering owner...")
owner_resp = requests.post(f"{BASE_URL}/customer/register", data={
    "name": "Owner User",
    "email": owner_email,
    "password": "password123",
    "role": "owner"
})
if owner_resp.status_code != 200:
    print(f"Registration failed: {owner_resp.text}")
    exit(1)

owner_id = owner_resp.json()["id"]
print(f"✅ Owner registered: {owner_id}")

# Step 1b: Login as owner
print("\n[1b/7] Owner logging in...")
owner_login = requests.post(f"{BASE_URL}/customer/login", data={
    "email": owner_email,
    "password": "password123"
})
owner_token = owner_login.json()["token"]
print(f"✅ Owner logged in")

# Step 2: Create organization
print("\n[2/7] Creating organization...")
org_resp = requests.post(f"{BASE_URL}/customer/create-customer", 
    headers={"Authorization": f"Bearer {owner_token}"},
    data={
        "name": "SQL Test Company",
        "organization_password": "org-password-123"
    }
)
org_id = org_resp.json()["customer_id"]
print(f"✅ Organization created: {org_id}")

# Step 3: Create employee
print("\n[3/7] Creating employee...")
emp_resp = requests.post(f"{BASE_URL}/customer/create-user",
    headers={"Authorization": f"Bearer {owner_token}"},
    data={
        "name": "Employee User",
        "email": emp_email,
        "password": "password123",
        "role": "employee",
        "customer_id": org_id
    }
)
print(f"✅ Employee created")

# Step 4: Employee login
print("\n[4/7] Employee logging in...")
emp_login = requests.post(f"{BASE_URL}/customer/login", data={
    "email": emp_email,
    "password": "password123"
})
emp_token = emp_login.json()["token"]
print(f"✅ Employee logged in")

# Step 5: Upload test Excel file
print("\n[5/7] Uploading Excel file...")

# Create test Excel file
import openpyxl
from io import BytesIO

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Sales"

# Headers
ws['A1'] = "Date"
ws['B1'] = "Product"
ws['C1'] = "Quantity"
ws['D1'] = "Price"
ws['E1'] = "Total"

# Data rows
data = [
    ["2024-01-15", "Laptop Computer", 5, 999.99, 4999.95],
    ["2024-01-16", "Wireless Mouse", 12, 29.99, 359.88],
    ["2024-01-17", "USB-C Hub", 8, 49.99, 399.92],
    ["2024-01-18", "Laptop Computer", 3, 999.99, 2999.97],
    ["2024-01-19", "Wireless Mouse", 25, 29.99, 749.75],
]

for idx, row in enumerate(data, start=2):
    for col, value in enumerate(row, start=1):
        ws.cell(row=idx, column=col).value = value

# Save to BytesIO
excel_bytes = BytesIO()
wb.save(excel_bytes)
excel_bytes.seek(0)

upload_resp = requests.post(
    f"{BASE_URL}/customer/{org_id}/upload",
    headers={"Authorization": f"Bearer {emp_token}"},
    files={"file": ("sales_data.xlsx", excel_bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")},
    data={"organization_password": "org-password-123"}
)

upload_data = upload_resp.json()
print(f"✅ Excel file uploaded")
print(f"   - File ID: {upload_data.get('file_id')}")
print(f"   - Chunks: {upload_data.get('chunks')}")
print(f"   - File Type: {upload_data.get('file_type')}")

# Step 6: Wait for embeddings
print("\n[6/7] Waiting for embeddings to complete (10 seconds)...")
time.sleep(10)

# Step 7: Ask Q&A questions (Excel-specific)
print("\n[7/7] Asking Q&A questions (will generate SQL queries)...")

questions = [
    "What is the total revenue from Laptop Computer sales?",
    "How many Wireless Mouse units were sold in total?",
    "What is the most expensive product?",
    "List all transactions sorted by date",
]

for i, question in enumerate(questions, 1):
    print(f"\n{'─' * 80}")
    print(f"Question {i}: {question}")
    print(f"{'─' * 80}")
    
    qa_resp = requests.post(
        f"{BASE_URL}/customer/{org_id}/ask",
        headers={"Authorization": f"Bearer {emp_token}"},
        data={
            "query": question,
            "top_k": 10,
            "organization_password": "org-password-123"
        }
    )
    
    if qa_resp.status_code == 200:
        result = qa_resp.json()
        
        print(f"\n✅ QUERY TYPE: {result.get('query_type', 'N/A')}")
        print(f"✅ RETRIEVED CHUNKS: {result.get('retrieved_chunks', 0)}")
        
        # Show structured answer details
        if 'structured_answer' in result:
            struct = result['structured_answer']
            print(f"\n📊 SQL QUERY GENERATED:")
            print(f"   {struct.get('sql', 'N/A')}")
            
            print(f"\n📋 SQL EXECUTION RESULTS:")
            rows = struct.get('rows', [])
            if rows:
                for row in rows:
                    print(f"   {row}")
            else:
                print("   (No results)")
        
        print(f"\n💬 ANSWER:")
        print(f"   {result.get('answer', 'N/A')}")
        
        print(f"\n📁 SOURCES:")
        for source in result.get('sources', []):
            print(f"   - {source}")
    else:
        print(f"❌ Error: {qa_resp.status_code}")
        print(qa_resp.text)

print("\n" + "=" * 80)
print("TEST COMPLETE")
print("=" * 80)
print("\nKey Points:")
print("✅ Each Excel row is stored as 1 chunk (5 rows = 5 chunks)")
print("✅ LLM receives all chunks and generates SQL query")
print("✅ Backend executes the SQL query against in-memory SQLite")
print("✅ Structured results are returned with the SQL query visible")
print("✅ You can see the exact SQL that was generated and executed")
